//
// Created by Anthony Grieco on 2/23/2021.
//

#ifndef PROBLEM_2_CPP_RANDOMNUMBERGENERATOR_H
#define PROBLEM_2_CPP_RANDOMNUMBERGENERATOR_H

#endif //PROBLEM_2_CPP_RANDOMNUMBERGENERATOR_H

int randNumGen(bool);